Update-docs
DEWETRON/OXYGEN-SDK pull request #32
Opened 2023-11-07 11:27 UTC by mpobaschnig

2023-11-08 15:50 UTC, matthiasstraka requested changes

2023-11-08 15:50 UTC, matthiasstraka commented on docs/01_SDKIntroduction/SDKIntroduction.rst
> + * Ubuntu 20.04 LTS Linux (Focal Fossa) and 22.04 LTS Linux (Jammy Jallyfish)
Jellyfish

2023-11-08 15:50 UTC, matthiasstraka commented on docs/02_Quickstart/Quickstart.rst
> +- Ubuntu 20.04 LTS Linux (Focal Fossa) or Ubuntu 22.04 LTS Linux (Jammy Jallyfish)
Jellyfish

2023-11-09 05:59 UTC, mpobaschnig commented on docs/01_SDKIntroduction/SDKIntroduction.rst
> + * Ubuntu 20.04 LTS Linux (Focal Fossa) and 22.04 LTS Linux (Jammy Jallyfish)
Done.

2023-11-09 05:59 UTC, mpobaschnig commented on docs/02_Quickstart/Quickstart.rst
> +- Ubuntu 20.04 LTS Linux (Focal Fossa) or Ubuntu 22.04 LTS Linux (Jammy Jallyfish)
Done.

2024-10-28 08:25 UTC, matthiasstraka approved these changes

2024-10-28 08:26 UTC, matthiasstraka approved these changes

2024-10-28 08:27 UTC, merged